from typing import Any, Dict, Mapping

from sqlalchemy.orm import Session

from .generator import (
    generate_summary_reports,
    generate_technical_reports,
    generate_architecture_reports,
    generate_all_reports,
)


def _build_common_meta(run_id: str) -> Dict[str, Any]:
    # In a later pass, pull client name, project name, etc. from DB.
    return {
        "run_id": run_id,
        "title_prefix": "CloudReadyAI",
        "client_name": "Client Name (TODO: from DB)",
    }


def build_summary_context(db: Session, run_id: str) -> Dict[str, Any]:
    """
    TODO: Pull real data from ingestion + analysis + TCO.

    For now, we provide a stable stub so templates can render without errors.
    """
    meta = _build_common_meta(run_id)

    return {
        "meta": {
            "title": "Cloud Migration Assessment Summary",
            "client_name": meta["client_name"],
            "run_id": run_id,
        },
        "executive_summary": (
            "This is a placeholder executive overview generated by CloudReadyAI. "
            "In a later iteration, this will summarize key findings, migration "
            "strategy, and projected benefits for the client."
        ),
        "environment": {
            "stats": [
                {"label": "Total Servers", "value": 42},
                {"label": "Total vCPU", "value": "168 vCPU"},
                {"label": "Total RAM", "value": "1.5 TB"},
                {"label": "Total Storage", "value": "320 TB"},
                {"label": "Distinct Applications", "value": 12},
            ]
        },
        "r_score": {
            "overall": "B+",
            "notes": "Workloads are generally cloud-ready with some modernization required.",
        },
        "recommendations": [
            "Prioritize migration of low-risk, high-value workloads in Wave 1.",
            "Refactor legacy .NET applications to PaaS where feasible.",
            "Introduce centralized monitoring and logging in the target cloud.",
        ],
    }


def build_technical_context(db: Session, run_id: str) -> Dict[str, Any]:
    # TODO: Replace stub with actual detailed technical data
    meta = _build_common_meta(run_id)

    return {
        "meta": {
            "title": "Technical Assessment Report",
            "client_name": meta["client_name"],
            "run_id": run_id,
        },
        "executive_summary": (
            "This report provides a detailed breakdown of servers, storage, "
            "networking, and application dependencies for the assessed environment."
        ),
        "servers": [],
        "storage": [],
        "network": [],
        "dependencies": [],
    }


def build_architecture_context(db: Session, run_id: str) -> Dict[str, Any]:
    # TODO: Replace stub with actual target architecture details
    meta = _build_common_meta(run_id)

    return {
        "meta": {
            "title": "Target Cloud Architecture Report",
            "client_name": meta["client_name"],
            "run_id": run_id,
        },
        "executive_summary": (
            "This report outlines the proposed target cloud architecture, "
            "including landing zone design, networking, security, and data services."
        ),
        "target_cloud": "AWS",
        "landing_zone": {},
        "network_topology": {},
        "security_model": {},
        "data_platform": {},
        "migration_waves": [],
    }


def generate_summary(db: Session, run_id: str) -> Dict[str, Any]:
    ctx = build_summary_context(db, run_id)
    outputs = generate_summary_reports(run_id, ctx)
    return {
        "pdf_path": str(outputs["pdf"]),
        "docx_path": str(outputs["docx"]),
    }


def generate_technical(db: Session, run_id: str) -> Dict[str, Any]:
    ctx = build_technical_context(db, run_id)
    outputs = generate_technical_reports(run_id, ctx)
    return {
        "pdf_path": str(outputs["pdf"]),
        "docx_path": str(outputs["docx"]),
    }


def generate_architecture(db: Session, run_id: str) -> Dict[str, Any]:
    ctx = build_architecture_context(db, run_id)
    outputs = generate_architecture_reports(run_id, ctx)
    return {
        "pdf_path": str(outputs["pdf"]),
        "docx_path": str(outputs["docx"]),
    }


def generate_all(db: Session, run_id: str) -> Dict[str, Any]:
    """
    Generate all three report types plus the ZIP package.
    """
    contexts: Mapping[str, Dict[str, Any]] = {
        "summary": build_summary_context(db, run_id),
        "technical": build_technical_context(db, run_id),
        "architecture": build_architecture_context(db, run_id),
    }

    outputs = generate_all_reports(run_id, contexts)

    return {k: str(v) for k, v in outputs.items()}
